feat: CLIN-1779 add new dictionnary option for checkbox filter
Ferlab-Ste-Justine/ferlab-ui pull request #240
Opened 2023-03-05 19:30 UTC by oliviercperrier

# FEATURE

- closes CLIN-1779

## Validation de Qualité

- [X] Validation du design avec design figma (dev)
- [ ] QA - Validation des critère de succès (via screenshot)
- [ ] Design/UI - Validation du respect du design/theme

## Screenshot
https://user-images.githubusercontent.com/28421005/222981527-ad101734-d7d5-4199-9342-859228adb601.mov

## Mention
@luclemo @kstonge

2023-03-07 16:02 UTC, francisl requested changes
All good. Faut juste changer les double quotes à singles quotes comme le standard.
version 5.2.2
aussi fait un rebase avec 1 seul commit.

2023-03-07 16:02 UTC, francisl commented on storybook/stories/Components/Filters/CheckboxFilter.stories.tsx
> +    title: "CheckboxFilter No Data checkbox",
single quote - Le linter devrait attraper ca!

2023-03-07 16:48 UTC, atoulous approved these changes

2023-03-07 16:51 UTC, atoulous commented on packages/ui/src/data/sqon/utils.ts
> +import { cloneDeep, conforms, isEmpty, isUndefined, merge, union } from 'lodash';
tu as oublié de retirer conforms

2023-03-07 18:59 UTC, francisl commented on packages/ui/package.json
> +    "version": "5.2.1",
feature, devrait être 5.3.0 effectivement

2023-03-07 21:55 UTC, oliviercperrier commented on storybook/stories/Components/Filters/CheckboxFilter.stories.tsx
> +    title: "CheckboxFilter No Data checkbox",
@francisl J'ai bougé le prettierrc.js dans le root. Il y avait rien pour storybook c'est pour ca

2023-03-08 03:34 UTC, francisl approved these changes
🍺

2023-03-08 03:43 UTC, merged