feat: CLIN-1784 noData generateValueFilter
Ferlab-Ste-Justine/ferlab-ui pull request #256
Opened 2023-03-21 19:32 UTC by claudia1296

# [FEATURE] noData generateValueFilter

- closes CLIN-1784

## Description
Ajout de la possibilité de mettre noData pour lors de la création de rangeFilter

## Validation de Qualité

- [ ] Validation du design avec design figma (dev)
- [ ] QA - Validation des critère de succès (via screenshot)
- [ ] Design/UI - Validation du respect du design/theme

2023-03-21 19:49 UTC, creativeyann17 approved these changes

2023-03-21 20:23 UTC, francisl requested changes

2023-03-21 20:23 UTC, francisl commented on packages/ui/package.json
> +    "version": "5.4.6",
c'est une nouvelle fonctionnalité
donc 5.5.0
https://semver.org/

2023-03-21 20:23 UTC, francisl commented on packages/ui/src/data/sqon/utils.test.tsx
> +describe(`${isUploadedList.name}()`, () => {
?

2023-03-21 20:36 UTC, atoulous commented on packages/ui/src/data/sqon/utils.ts
> +    return !rangeFilterNoData
proposition clean code:
`const noDataFilter = {
              content: [basicFilter, noDataFilterContent],
              op: BooleanOperators.or,
              skipBooleanOperatorCheck: true,
          }
return rangeFilterNoData ? noDataFilter : basicFilter
`

2023-03-21 20:58 UTC, mobastille commented on packages/ui/src/data/sqon/utils.test.tsx
> +describe(`${isUploadedList.name}()`, () => {
C'est moi qui l'avait fait comme ça au départ mais on pourrait simplement mettre `describe('isUploadedList()', () => {`

C'est juste qu'on m'avait suggéré de le faire comme ça sur KF pour que ça donne une erreur dans le describe et pas oublié de faire le changement si jamais le nom de la fonction change. 

Mais c'est pas un gros gain ça pourrait être hardcodé à la place si vous pensez que c'est mieux pour la lisibilité.

2023-03-22 14:46 UTC, francisl approved these changes
🎆

2023-03-22 14:50 UTC, merged