fix(pagination): FLUI-29 FLUI-42 FLUI-39 fix searchafter
Ferlab-Ste-Justine/ferlab-ui pull request #263
Opened 2023-03-29 18:35 UTC by lflangis

#  BUG

- closes #[29](https://ferlab-crsj.atlassian.net/browse/FLUI-29)
- closes #[39](https://ferlab-crsj.atlassian.net/browse/FLUI-39)
- closes #[42](https://ferlab-crsj.atlassian.net/browse/FLUI-42)

## Description
Un fix client doit aussi être appliqué afin de retirer le searchafter lorsqu'on modifie la query

```
  useEffect(() => {
    if (selectedKeys.length) {
      setSelectedKeys([]);
      setSelectedRows([]);
    }

    resetSearchAfterQueryConfig(
      {
        ...DEFAULT_QUERY_CONFIG,
        sort: DEFAULT_BIOSPECIMEN_QUERY_SORT,
        size:
          userInfo?.config?.data_exploration?.tables?.biospecimens?.viewPerQuery ||
          DEFAULT_PAGE_SIZE,
      },
      setQueryConfig,
    );
    setPageIndex(DEFAULT_PAGE_INDEX);

    // eslint-disable-next-line
  }, [JSON.stringify(activeQuery)]);
```

Acceptance Criterias

## Validation de Qualité
- [ ] QA - Validation des critère de succès (via screenshot)

## Screenshot

https://user-images.githubusercontent.com/65532894/228635245-c32694ec-a7f7-458b-a85f-c534832a4c4e.mp4

https://user-images.githubusercontent.com/65532894/228635246-a047a4fa-7148-497c-a4d8-c538beb3bab2.mp4

https://user-images.githubusercontent.com/65532894/228635249-7114c362-300c-4323-a033-20ec9b2b447a.mp4

## Mention
@kstonge

2023-03-29 19:48 UTC, francisl requested changes

2023-03-29 19:48 UTC, francisl commented on packages/ui/package.json
> +    "version": "5.5.4",
déjà la version 5.5.6 de publié

2023-03-29 19:48 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-empty-function
au lieu de désactivé la règle, la façon recommendé c'est d'expliquer la raison.

e.g.

```javascript
// eslint-disable-next-line @typescript-eslint/no-empty-function
onClearSelection: () => {},
```

vers 

```javascript
onClearSelection: () => {
    // optional function when omit
},
```

de cette façon c'est clair.

2023-03-29 19:48 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
si on veux avoir un validation correct des nulls pour limiter certains type de bug, il faut utilisé l'opérateur a cette effect. `??`.

2023-03-29 19:48 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +                // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
☝️

2023-03-29 19:48 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +                        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
☝️

2023-03-29 19:48 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +                    loading={loading ? true : false}
loading est déjà un boolean et n'est pas optionnel

2023-03-29 20:09 UTC, lflangis commented on packages/ui/package.json
> +    "version": "5.5.4",
Aucun tags n'a été créé pour ces versions et master est sur 5.5.3. Je ne sais pas qui s'en charge mais pourrait-on merger ces versions avant que je merge la mienne pour éviter d'écraser des fix?

2023-03-29 20:09 UTC, lflangis commented on packages/ui/src/components/ProTable/index.tsx
> +        // eslint-disable-next-line @typescript-eslint/no-empty-function
Ça me semble alourdir le code avec des commentaires sans grande utilité (ici 4 fonctions avec 4 fois le même commentaire). Est-ce que la règle ne devrait simplement pas être retirer sur les no-empty-function?

2023-03-30 15:28 UTC, francisl approved these changes
:shipit:

2023-03-30 15:31 UTC, merged