feat: CQDG-490 Add Popover on ProTable title
Ferlab-Ste-Justine/ferlab-ui pull request #359
Opened 2023-11-29 18:46 UTC by atoulous

# feat: CQDG-490 Add Popover on ProTable title

- closes #TICKET_NUMBER

## Description

https://ferlab-crsj.atlassian.net/browse/CQDG-490

Acceptance Criterias

## Validation

- [ ] Storybook add or modified
- [ ] version Update in package.json and Release.md
- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
### Before

### After

## QA

Steps to validate
Url (storybook, ...)
...

## Mention

2023-11-29 18:47 UTC, atoulous commented on packages/ui/src/components/ProTable/index.tsx
> +        title = column.popoverProps ? <Popover {...column.popoverProps}>{column.title}</Popover> : title;
```  {
    key: 'age_biospecimen_collection2',
    dataIndex: 'age_biospecimen_collection',
    sorter: { multiple: 1 },
    title: intl.get('entities.biospecimen.age'),
    tooltip: intl.get('entities.biospecimen.age_biospecimen_collection'),
    popoverProps: {
    ```
si tooltip et popoverProps sont fourni, Popover > Tooltip

2023-11-29 19:39 UTC, AltefrohneGaelle commented on packages/ui/package.json
> +    "version": "7.15.0",
Est ce que tu passes à une nouvelle mineure car la version de correction est à 15 ? C'est plus de la curiosité là car je en sais pas à quel moment on change. Et est ce que tu peux faire un npm install pour avoir ta nouvelle version dans la package json lock stp.

2023-11-29 19:39 UTC, AltefrohneGaelle commented on packages/ui/src/components/ProTable/index.tsx
> +        title = column.popoverProps ? <Popover {...column.popoverProps}>{column.title}</Popover> : title;
Il y a un truc qui me perturbe la variable title est définie 4 fois de suite et utilisée dans elle même dans la deuxième définition. Et la une et la 3 se base sur la meme variable tooltip mais donne des valeurs différentes. Je ne sais pas comment mais c'est améliorable non ? Et c'est exactement le même code plus bas dans ExpandableTable/index est ce qu'on pourrait extraire ça dans un utils ?

2023-11-29 19:42 UTC, francisl commented on packages/ui/package.json
> +    "version": "7.15.0",
https://semver.org/

2023-11-29 19:57 UTC, atoulous commented on packages/ui/package.json
> +    "version": "7.15.0",
La Minor se mérite car je rajoute une fonctionnalité.
Selon moi on a fait trop de patch deja sur la 14.
Ca aurait presque pu etre une Major car j'ai bridé le type de `title` sur ProColumnType, mais on l'utilisait que en string anyway donc ca sera pas bloquant.

2023-11-29 20:12 UTC, lflangis commented on packages/ui/src/components/ProTable/index.tsx
> +        title = column.popoverProps ? <Popover {...column.popoverProps}>{column.title}</Popover> : title;
Afin de réduire les risques mais d'augmenter la lisibilité, on pourrait peut-être simplement transformer les checks ternaires en quelques choses de plus lisibile. 

@francisl vue que c'est risqué, si on compte qu'avec storybook et nos tests, peut-on se permettre quelques refacto sur des cas comme celui-ci?

2023-11-29 20:14 UTC, francisl requested changes

2023-11-29 20:14 UTC, francisl commented on packages/ui/src/components/ProTable/index.tsx
> +        title = column.popoverProps ? <Popover {...column.popoverProps}>{column.title}</Popover> : title;
je comprend l'idée, mais je trouve que ca demande de la gymastique pour vraiment se faire l'idée de l'état attendu.

Aussi, aucun raison de faire tout calcule si tu sais déjà que popoverProps n'en a pas besoin
```typescript

   if (column.popoverProps) {
       return <Popover {...column.popoverProps}>{column.title}</Popover> 
    }

    const titleToUse = column.icon && !column.iconTitle ? (
            <Space size={3}>
                {column.icon} {title}
            </Space>
        ) : column.title;

    return column.tooltip ? 
        <Tooltip title={column.tooltip}>
            <span style={{ borderBottom: '1px dotted' }}>
                {titleToUse}
            </span> 
        </Tooltip>
        : titleToUse;

```

2023-11-29 20:14 UTC, francisl commented on packages/ui/src/components/tables/ExpandableTable/index.tsx
>          return { ...column, title } as ProColumnType;
Même chose ici. il n'y a pas de valeur à tout 'processer' pour potentiellement aucune raison.

2023-11-29 20:16 UTC, atoulous commented on packages/ui/src/components/ProTable/index.tsx
> +        let title = column.tooltip ? <span style={{ borderBottom: '1px dotted' }}>{titleToUse}</span> : titleToUse;
c'etait deja present

2023-11-29 20:59 UTC, atoulous commented on packages/ui/src/components/ProTable/index.tsx
> +        title = column.popoverProps ? <Popover {...column.popoverProps}>{column.title}</Popover> : title;
Refont de `getTitleByType `

2023-11-29 21:11 UTC, AltefrohneGaelle commented on packages/ui/src/components/tables/ExpandableTable/index.module.scss
> +.dotted {
je ne crois pas ce style est utilisé comme tu utilise la methode de ProTable qui a son propre style ou j'ouvre pas les yeux ce qui est possible en ce moment 😄

2023-11-29 21:13 UTC, atoulous commented on packages/ui/src/components/tables/ExpandableTable/index.module.scss
> +.dotted {
Si on fait ici:
```
<Popover className={styles.dotted}
<Tooltip className={styles.dotted}
```

2023-11-29 21:17 UTC, AltefrohneGaelle approved these changes

2023-11-29 21:19 UTC, francisl requested changes
juste ajouter le usecase du popover dans les storybooks

2023-11-30 12:05 UTC, francisl approved these changes
:shipit:

2023-11-30 14:16 UTC, merged