feat: FLUI-60 add draggable props to ResizableGridCard
Ferlab-Ste-Justine/ferlab-ui pull request #381
Opened 2024-01-29 20:43 UTC by aperron-ferlab

# FEAT: FLUI-60 add draggable props to ResizableGridCard

- closes [#FLUI-60](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-60)

## Description

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-60)

Acceptance Criterias

## Validation

- [ ] Storybook add or modified
- [ ] version Update in package.json and Release.md
- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

2024-01-29 21:41 UTC, AltefrohneGaelle commented
Dans une PR ferlab il faut que tu mettes as jour la version dans le package json et que tu décrives ce que tu ajoutes dans la version dans le fichier Release.md stp

2024-01-30 12:35 UTC, lflangis requested changes

2024-01-30 12:35 UTC, lflangis commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
> +            <div className={draggable ? 'rgl-drag-zone' : ''}>
ici tu peux utiliser classnames au lieu d'un ternaire
```suggestion
            <div className={classnames({'rgl-drag-zone': draggable})>
```

2024-01-30 13:47 UTC, aperron-ferlab commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
> +            <div className={draggable ? 'rgl-drag-zone' : ''}>
Je connaissais pas classnames, j'ai mis a jour avec le changement!

2024-01-30 13:56 UTC, AltefrohneGaelle commented on packages/ui/Release.md
> +-   feat: FLUI-60 add draggable props to ResizableGridCard
Étrange que ça ait reformaté tout le fichier tu n'as peut être pas la même config que nous.

2024-01-30 14:06 UTC, aperron-ferlab commented on packages/ui/Release.md
> +-   feat: FLUI-60 add draggable props to ResizableGridCard
En effet étrange je vais regarder ca

2024-01-30 14:38 UTC, atoulous commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
>      withHandle = false,
withHandle c'etait pas pour la meme chose ? On a besoin de garder les 2 ?

2024-01-30 14:41 UTC, aperron-ferlab commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
>      withHandle = false,
En quelque sorte cest une duplication mais si on enleve un props ca devient un breaking change vu que les intégrations vont crash.

2024-01-30 15:13 UTC, aperron-ferlab commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
>      withHandle = false,
https://ferlab-crsj.atlassian.net/jira/software/c/projects/FLUI/boards/7?selectedIssue=FLUI-60

Pour matcher avec ce qui etait demandé dans la story

2024-01-30 15:24 UTC, lflangis commented on packages/ui/src/view/v2/GridCard/GridCardHeader/index.tsx
>      withHandle = false,
Pardon, j'ai relu le jira et je pense qu'elle a été créé sans savoir que c'est déjà supporté par react-grid-layout. On peut rendre une carte draggable ou non via la props isDraggable qu'on passe dans la config de la carte. Ça permet ainsi de déterminer qu'elle carte peut-être bouger ou non.

```
    base: {
      h: 2,
      minH: 2,
      minW: 4,
      w: 8,
      x: 0,
      y: 4,
      isDraggable: false,
    },
```

Cependant j'ai vue les points d'améliorations suivant

Lorsqu'une carte n'est pas draggable, on devrait automatiquement cacher l'handle et retirer le classe css qui change le cursor
https://github.com/Ferlab-Ste-Justine/ferlab-ui/assets/65532894/3b18c3b8-b8a9-4110-aeda-4a45863659ba

2024-01-30 16:04 UTC, atoulous approved these changes
lgtm

2024-01-30 16:05 UTC, lflangis approved these changes

2024-01-30 16:24 UTC, AltefrohneGaelle approved these changes

2024-01-30 18:55 UTC, merged