Feat/improve pro label
Ferlab-Ste-Justine/ferlab-ui pull request #545
Opened 2024-11-06 21:01 UTC by oliviercperrier

# FEAT

- relates to CLIN-2923

## Description

Make ProLabel supports Popover and Tooltip for the info icon.

[[JIRA LINK]](https://ferlab-crsj.atlassian.net/browse/CLIN-2923)

Acceptance Criterias

## Validation

- [ x] Storybook add or modified
- [ x] version Update in package.json and Release.md
- [ ] Code Approved
- [ ] QA Done
- [ ] Design/UI Approved from design

## Screenshot
<img width="374" alt="Screenshot 2024-11-06 at 4 00 26 PM" src="https://github.com/user-attachments/assets/47508f42-1314-4f58-8037-06901d11c2c6">

## Mention

@kstonge @luclemo

2024-11-06 21:10 UTC, AltefrohneGaelle requested changes

2024-11-06 21:10 UTC, AltefrohneGaelle commented on packages/ui/package.json
> +    "version": "10.11.1",
tu ne dois pas être à jour en local car cette version existe déjà.

2024-11-06 21:26 UTC, oliviercperrier commented on packages/ui/package.json
> +    "version": "10.11.1",
Possible, je regardes merci

2024-11-06 23:16 UTC, oliviercperrier commented on packages/ui/package.json
> +    "version": "10.11.1",
Done

2024-11-07 01:24 UTC, oliviercperrier commented on packages/ui/src/components/ProLabel/index.tsx
> +);
@atoulous Ca s'appel du conditinal typing c'est loin d'être chimique hahah.

tooltipProps ne peut pas être défini en meme temps que popoverProps, d'où le conditional typing.

2024-11-07 14:19 UTC, francisl approved these changes
👍

2024-11-07 14:19 UTC, AltefrohneGaelle approved these changes

2024-11-07 14:20 UTC, francisl commented
@oliviercperrier tu vas juste devoir faire un rebase et mettre a jour ta version a 10.13.0 (new features)

2024-11-07 15:20 UTC, atoulous commented on packages/ui/src/components/ProLabel/index.tsx
> +);
Garde comme ça si c'est ce que tu préconises 👍
Selon moi l'optional typing suffisait, mais pour le conditional je te partage une solution que je trouve plus lisible avec du naming

```
interface IProLabelBaseProps {
    title: string;
    className?: string;
    colon?: boolean;
    size?: 'small' | 'default';
    requiredMark?: boolean;
}

interface IProLabelWithPopover extends IProLabelBaseProps {
    popoverProps: PopoverProps;
    tooltipProps?: never;
}

interface IProLabelWithTooltip extends IProLabelBaseProps {
    tooltipProps: TooltipProps;
    popoverProps?: never;
}

export type IProLabelProps = IProLabelWithPopover | IProLabelWithTooltip;

2024-11-07 15:37 UTC, oliviercperrier commented on packages/ui/src/components/ProLabel/index.tsx
> +);
Sinon, voici ce que j'ai fait

```
interface IProLabelWithPopover {
    popoverProps?: PopoverProps;
    tooltipProps?: never;
}

interface IProLabelWithTooltip {
    popoverProps?: never;
    tooltipProps?: TooltipProps;
}

export type IProLabelProps = {
    title: string;
    className?: string;
    colon?: boolean;
    size?: 'small' | 'default';
    requiredMark?: boolean;
} & (IProLabelWithPopover | IProLabelWithTooltip);
```

2024-11-07 15:43 UTC, atoulous approved these changes

2024-11-07 15:48 UTC, merged